name : Rohit Workflow
on:
  pull_request:
    branches: ['main']

jobs:
  rohit-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install chrome browser
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - name: Run Rohit Script
        run: |
          cd Rohit/Headless_in_Framework
          pip install -r requirements.txt
          python -m pytest -v --headless=True --browser_name="chrome" ./Tests/ --html=report.html --self-contained-html

      - name : Upload Rohit Test Report    
        if : always()
        uses : actions/upload-artifact@v4
        with:
            name : Rohit Test Report
            path : Rohit/Headless_in_Framework/report.html